<a href="https://colab.research.google.com/github/amir-b-mostaghimi/Hackthon-Shinkansen-Travel-Experience-/blob/master/hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np                              
import pandas as pd

# Basic library for data visualization
import matplotlib.pyplot as plt     

# Slightly advanced library for data visualization            
import seaborn as sns                          

# Featauretools for feature engineering


from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Importing gradient boosting regressor, to make prediction
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor


# Used to ignore the warning given as output of the code
import warnings
warnings.filterwarnings("ignore")


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
# Read the data
df_sur_train = pd.read_csv("Surveydata_train.csv",  encoding='utf-8')
df_trav_train = pd.read_csv("Traveldata_train.csv", encoding='utf-8')
data_f_train = pd.concat([df_trav_train, df_sur_train ], axis=1, join='inner')

data_f_train=data_f_train.drop('ID',1)
#data_f_train=data_f_train.drop('Arrival_Delay_in_Mins',1)
#___________________________________________________________________________________________________________________________________________________________________

df_sur_test = pd.read_csv("Surveydata_test.csv",  encoding='utf-8')
df_trav_test = pd.read_csv("Traveldata_test.csv", encoding='utf-8')
data_f_test = pd.concat([df_trav_test, df_sur_test ], axis=1, join='inner')

data_f_test=data_f_test.drop('ID',1)
#data_f_test=data_f_test.drop('Arrival_Delay_in_Mins',1)

print(data_f_train.isnull().sum().sum())

44597


In [ ]:
#Outlayer detection

fig, ax =plt.subplots(1,4, figsize=(16,8))
sns.boxplot(df_imputed_train['Age'], ax=ax[0])
sns.boxplot(df_imputed_train['Departure_Delay_in_Mins'], ax=ax[1])
sns.boxplot(df_imputed_train['Arrival_Delay_in_Mins'], ax=ax[2])
sns.boxplot(df_imputed_train['Travel_Distance'], ax=ax[3])

fig.show()

#___________________________________________________________________________________________________________________________________________________________________


fig, ax =plt.subplots(1,4, figsize=(16,8))
sns.boxplot(df_imputed_test['Age'], ax=ax[0])
sns.boxplot(df_imputed_test['Departure_Delay_in_Mins'], ax=ax[1])
sns.boxplot(df_imputed_test['Arrival_Delay_in_Mins'], ax=ax[2])
sns.boxplot(df_imputed_test['Travel_Distance'], ax=ax[3])

#fig.show()

###Encoding

In [ ]:
# Label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for cat_var in ['Gender','Customer_Type','Type_Travel','Travel_Class','Seat_Comfort','Arrival_Time_Convenient','Catering','Platform_Location','Onboard_Wifi_Service','Onboard_Entertainment','Online_Support','Ease_of_Online_Booking','Onboard_Service','Legroom',
                                                         'Baggage_Handling','CheckIn_Service','Cleanliness','Online_Boarding','Seat_Class']:
    data_f_train[cat_var] = le.fit_transform(data_f_train[cat_var])  
label_encoded_train= data_f_train
label_encoded_train

#___________________________________________________________________________________________________________________________________________________________________


for cat_var in ['Gender','Customer_Type','Type_Travel','Travel_Class','Seat_Comfort','Arrival_Time_Convenient','Catering','Platform_Location','Onboard_Wifi_Service','Onboard_Entertainment','Online_Support','Ease_of_Online_Booking','Onboard_Service','Legroom',
                                                         'Baggage_Handling','CheckIn_Service','Cleanliness','Online_Boarding','Seat_Class']:
    data_f_test[cat_var] = le.fit_transform(data_f_test[cat_var])  
label_encoded_test= data_f_test
label_encoded_test



Gender  Customer_Type   Age  Type_Travel  Travel_Class  \
0           0              2  36.0            0             0   
1           0              0  21.0            0             0   
2           1              1  60.0            0             0   
3           0              1  29.0            1             1   
4           1              0  18.0            0             0   
...       ...            ...   ...          ...           ...   
35597       1              1   8.0            1             1   
35598       0              1  53.0            0             0   
35599       1              0  22.0            0             1   
35600       0              1  67.0            1             1   
35601       1              2  20.0            1             1   

       Travel_Distance  Departure_Delay_in_Mins  Arrival_Delay_in_Mins  \
0                  532                      0.0                    0.0   
1                 1425                      9.0                   28.0   
2                 2832                      0.0                    0.0   
3                 1352                      0.0                    0.0   
4                 1610                     17.0                    0.0   
...                ...                      ...                    ...   
35597             1334                      0.0                    0.0   
35598             1772                      0.0                    0.0   
35599             1180                      0.0                    0.0   
35600              420                     23.0                   16.0   
35601             1680                      0.0                    0.0   

       Seat_Comfort  Seat_Class  ...  Onboard_Wifi_Service  \
0                 0           0  ...                     4   
1                 2           1  ...                     0   
2                 1           1  ...                     1   
3                 0           0  ...                     5   
4                 1           1  ...                     1   
...             ...         ...  ...                   ...   
35597             4           0  ...                     0   
35598             4           1  ...                     0   
35599             3           0  ...                     4   
35600             1           1  ...                     0   
35601             3           1  ...                     5   

       Onboard_Entertainment  Online_Support  Ease_of_Online_Booking  \
0                          1               2                       1   
1                          5               0                       0   
2                          1               1                       4   
3                          0               1                       5   
4                          1               1                       1   
...                      ...             ...                     ...   
35597                      4               0                       0   
35598                      1               1                       3   
35599                      3               4                       4   
35600                      1               2                       1   
35601                      3               4                       5   

       Onboard_Service  Legroom  Baggage_Handling  CheckIn_Service  \
0                    1        1                 1                2   
1                    1        0                 2                0   
2                    3        4                 3                2   
3                    0        4                 1                1   
4                    5        0                 1                1   
...                ...      ...               ...              ...   
35597                2        1                 2                0   
35598                2        3                 2                0   
35599                4        0                 4                4   
35600                1     

In [ ]:
# Hot_encoding (Very nad performance)


one_hot_encoded_data_train= pd.get_dummies(data_f_train,columns=['Gender','Customer_Type','Type_Travel','Travel_Class','Seat_Comfort','Arrival_Time_Convenient','Catering','Platform_Location','Onboard_Wifi_Service','Onboard_Entertainment','Online_Support','Ease_of_Online_Booking','Onboard_Service','Legroom',
                                                         'Baggage_Handling','CheckIn_Service','Cleanliness','Online_Boarding','Seat_Class'])
one_hot_encoded_data_train

#___________________________________________________________________________________________________________________________________________________________________


one_hot_encoded_data_test= pd.get_dummies(data_f_test,columns=['Gender','Customer_Type','Type_Travel','Travel_Class','Seat_Comfort','Arrival_Time_Convenient','Catering','Platform_Location','Onboard_Wifi_Service','Onboard_Entertainment','Online_Support','Ease_of_Online_Booking','Onboard_Service','Legroom',
                                                         'Baggage_Handling','CheckIn_Service','Cleanliness','Online_Boarding','Seat_Class'])
one_hot_encoded_data_test

### Dealing with missing values

In [ ]:
#check to see which columns are missing values

label_encoded_test.columns[label_encoded_test.isnull().any()]
label_encoded_train.columns[label_encoded_train.isnull().any()]

#The missing values are numeric so we can use mean to fill them in

Index(['Age', 'Departure_Delay_in_Mins', 'Arrival_Delay_in_Mins'], dtype='object')

In [ ]:
# Imputing with mean


label_encoded_train['Age'] = label_encoded_train['Age'].fillna((label_encoded_train['Age'].mean()))
label_encoded_train['Departure_Delay_in_Mins'] = label_encoded_train['Departure_Delay_in_Mins'].fillna((label_encoded_train['Departure_Delay_in_Mins'].mean()))
label_encoded_train['Departure_Delay_in_Mins'] = label_encoded_train['Departure_Delay_in_Mins'].fillna((label_encoded_train['Departure_Delay_in_Mins'].mean()))
label_encoded_train_mean= label_encoded_train

label_encoded_test['Age'] = label_encoded_test['Age'].fillna((label_encoded_test['Age'].mean()))
label_encoded_test['Departure_Delay_in_Mins'] = label_encoded_test['Departure_Delay_in_Mins'].fillna((label_encoded_test['Departure_Delay_in_Mins'].mean()))
label_encoded_test['Departure_Delay_in_Mins'] = label_encoded_test['Departure_Delay_in_Mins'].fillna((label_encoded_test['Departure_Delay_in_Mins'].mean()))
label_encoded_test_mean= label_encoded_test
print(label_encoded_test_mean.isnull().any())


Gender                     False
Customer_Type              False
Age                        False
Type_Travel                False
Travel_Class               False
Travel_Distance            False
Departure_Delay_in_Mins    False
Seat_Comfort               False
Seat_Class                 False
Arrival_Time_Convenient    False
Catering                   False
Platform_Location          False
Onboard_Wifi_Service       False
Onboard_Entertainment      False
Online_Support             False
Ease_of_Online_Booking     False
Onboard_Service            False
Legroom                    False
Baggage_Handling           False
CheckIn_Service            False
Cleanliness                False
Online_Boarding            False
dtype: bool


In [ ]:
# Imputing with the most frequent

label_encoded_train_IMP=label_encoded_train.mask(label_encoded_train == '')
label_encoded_train_IMP = label_encoded_train_IMP.apply(lambda x: x.fillna(x.value_counts().index[0]))
#label_encoded_train_IMP= label_encoded_train_IMP.drop('ID',1)
label_encoded_train_IMP

#___________________________________________________________________________________________________________________________________________________________________


label_encoded_test_IMP = label_encoded_test.mask(data_f_test == '')
label_encoded_test_IMP = label_encoded_test_IMP.apply(lambda x: x.fillna(x.value_counts().index[0]))
#label_encoded_test_IMP= label_encoded_test_IMP.drop('ID',1)
label_encoded_test_IMP


In [ ]:
#droping data(very bad)

label_encoded_train_droped= label_encoded_train.dropna()
label_encoded_train_droped= label_encoded_train_droped.drop('ID',1)
label_encoded_test_droped= label_encoded_test.dropna() # This is not working! Answer to all the data set must be provided. So I will impute this one.

In [ ]:
y_data= one_hot_encoded_data_train['Overall_Experience']
x_data= one_hot_encoded_data_train.drop('Overall_Experience',1)

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data ,test_size = 0.2, shuffle=False)

In [ ]:
# KNN

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
imputer.fit(label_encoded_train)
arr = imputer.transform(label_encoded_train)
label_encoded_train = pd.DataFrame(arr, columns = label_encoded_train.columns, index = label_encoded_train.index)

#_____________________________________________________________________________________________________


imputer = KNNImputer(n_neighbors=3)
imputer.fit(label_encoded_test)
arr = imputer.transform(label_encoded_test)
label_encoded_test = pd.DataFrame(arr, columns = label_encoded_test.columns, index = label_encoded_test.index)

### Algorithms

In [ ]:
# Logestic regression

from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
lr = LogisticRegression(random_state=16)

# fit the model with data
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)


# import the metrics class
from sklearn.metrics import classification_report
target_names = ['unhappy', 'happy']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     unhappy       0.88      0.87      0.87      8555
       happy       0.89      0.90      0.90     10321

    accuracy                           0.89     18876
   macro avg       0.89      0.89      0.89     18876
weighted avg       0.89      0.89      0.89     18876



In [ ]:
#Naive Bayes 

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

y_pred  =  classifier.predict(x_test)

target_names = ['unhappy', 'happy']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     unhappy       0.98      0.05      0.10      8555
       happy       0.56      1.00      0.72     10321

    accuracy                           0.57     18876
   macro avg       0.77      0.53      0.41     18876
weighted avg       0.75      0.57      0.44     18876



In [ ]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=8)

#Train the model using the training sets
knn.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(x_test)

target_names = ['unhappy', 'happy']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     unhappy       0.91      0.94      0.93      8555
       happy       0.95      0.93      0.94     10321

    accuracy                           0.93     18876
   macro avg       0.93      0.93      0.93     18876
weighted avg       0.93      0.93      0.93     18876



In [ ]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(criterion="entropy", max_depth=7)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

target_names = ['unhappy', 'happy']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     unhappy       0.87      0.89      0.88      8555
       happy       0.91      0.89      0.90     10321

    accuracy                           0.89     18876
   macro avg       0.89      0.89      0.89     18876
weighted avg       0.89      0.89      0.89     18876



In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

target_names = ['unhappy', 'happy']
print(classification_report(y_test, y_pred, target_names=target_names))

###Test data (hot_encoded)

In [ ]:
test=list(one_hot_encoded_data_test)
train=list(one_hot_encoded_data_train)

res = [ ele for ele in train ]
for a in test:
  if a in train:
    res.remove(a)
res
 
for i in res:
  if i == 'Overall_Experience':
    pass
  else:
    one_hot_encoded_data_test[i] = 0



In [ ]:
# Test and train data
y_train= one_hot_encoded_data_train['Overall_Experience']
x_train= one_hot_encoded_data_train.drop('Overall_Experience',1)
x_test= one_hot_encoded_data_test

In [ ]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=8)

#Train the model using the training sets
knn.fit(x_train, y_train)

#Predict the response for test dataset
y_pred_KNN = knn.predict(x_test)

print (y_pred_KNN)


ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_KNN))

df_main = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_KNN})
df_main

df_main.to_csv('KNN.csv')

[1 1 1 ... 0 1 0]


In [ ]:
# Logestic regression

from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
lr = LogisticRegression(random_state=16)

# fit the model with data
lr.fit(x_train, y_train)

y_pred_lr = lr.predict(x_test)

print (y_pred_lr)


ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_lr))

df_lr = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_lr})
df_lr

df_lr.to_csv('lr.csv')

[0 0 1 ... 0 1 1]
35602 35602


In [ ]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion="entropy", max_depth=7)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred_clf = clf.predict(x_test)

ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_clf))

df_clf = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_clf})
df_clf

df_clf.to_csv('clf.csv')

35602 35602


###Test_data (label encoded)

In [ ]:
# Test and train data
y_train= label_encoded_train_mean['Overall_Experience']
x_train= label_encoded_train_mean.drop('Overall_Experience',1)
x_test= label_encoded_test_mean


res = [ ele for ele in x_train ]
for a in x_test:
  if a in x_train:
    res.remove(a)
res
 

[]

In [ ]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

#Train the model using the training sets
knn.fit(x_train, y_train)

#Predict the response for test dataset
y_pred_KNN = knn.predict(x_test)

print (y_pred_KNN)


ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_KNN))

df_KNN = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_KNN})
df_KNN

df_KNN.to_csv('KNN.csv')

[1 1 1 ... 1 1 0]
35602 35602


In [ ]:
# Logestic regression

from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
lr = LogisticRegression(random_state=16)

# fit the model with data
lr.fit(x_train, y_train)

y_pred_lr = lr.predict(x_test)

print (y_pred_lr)


ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_lr))

df_lr = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_lr})
df_lr

df_lr.to_csv('lr.csv')



[1 1 1 ... 0 1 0]
35602 35602


In [ ]:
importance = lr.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))



In [ ]:
# Random forest

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
rf.fit(x_train,y_train)

y_pred_rf=rf.predict(x_test)


y_pred_rf = rf.predict(x_test)

print (y_pred_rf)


ID = list(range(99900001, 99935603))
print(len(ID), len(y_pred_rf))

df_rf = pd.DataFrame({'ID':ID, 'Overall_Experience':y_pred_rf})
df_rf

df_rf.to_csv('rf.csv')

[1 1 1 ... 1 1 0]
35602 35602


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE



lr = LogisticRegression(solver='liblinear', random_state=123)

rfe = RFE(estimator=lr, n_features_to_select=10, step=1)
rfe.fit(x_train, y_train)

X_train_sub = rfe.transform(x_train)

small=label_encoded_train_mean.columns[1:][rfe.support_]
print(small)

res = [ ele for ele in label_encoded_train ]
for a in small:
  if a in label_encoded_train:
    res.remove(a)
res

Index(['Customer_Type', 'Age', 'Travel_Distance', 'Seat_Comfort',
       'Online_Support', 'Onboard_Service', 'Legroom', 'Baggage_Handling',
       'CheckIn_Service', 'Online_Boarding'],
      dtype='object')


['Gender',
 'Type_Travel',
 'Travel_Class',
 'Departure_Delay_in_Mins',
 'Arrival_Delay_in_Mins',
 'Overall_Experience',
 'Seat_Class',
 'Arrival_Time_Convenient',
 'Catering',
 'Platform_Location',
 'Onboard_Wifi_Service',
 'Onboard_Entertainment',
 'Ease_of_Online_Booking',
 'Cleanliness']

In [ ]:
# evaluate random forest algorithm for classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
# define dataset

# define the model
rand_forest_classifier_cv = RandomForestClassifier()
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(rand_forest_classifier_cv, x_train,y_train , scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

KeyboardInterrupt: ignored

In [ ]:
rand_forest_classifier_cv.fit(x_train, y_train)
model = rand_forest_classifier_cv
sub = pd.DataFrame(x_test)

res = model.predict(x_test)

sub["Overall_Experience"] = res #res = model.predict(dfTest)
sub_to_file = sub[["Overall_Experience"]]
sub_to_file.to_csv("rf_cl_cv_Day2_feature_eng.csv", index = True)
sub_to_file

Overall_Experience
0                       1
1                       1
2                       1
3                       0
4                       1
...                   ...
35597                   0
35598                   1
35599                   1
35600                   1
35601                   0

[35602 rows x 1 columns]